msg_success = "Success"
msg_wrongpwd = "Wrong account or password"
msg_badgateway = "Bad Gateway"
msg_unknown = "Unknown Error"
msg_connectionerror = "Service Unavailable. Connection error occurred."
msg_timeout = "Timeout"